abstract: Syntax suppor for XML literals
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.63
license: MIT
name: XML-Literal
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.6.0
version: 0.01
